// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_prog_4.Data;

#nullable disable

namespace Projet_prog_4.Migrations
{
    [DbContext(typeof(Projet_prog_4Context))]
    [Migration("20250415145611_CréationSiteWeb")]
    partial class CréationSiteWeb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_prog_4.Data.SiteWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbRestant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteWeb");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NbRestant = 0,
                            Nom = "SiteWeb1"
                        },
                        new
                        {
                            Id = 2,
                            NbRestant = 0,
                            Nom = "SiteWeb2"
                        },
                        new
                        {
                            Id = 3,
                            NbRestant = 0,
                            Nom = "SiteWeb3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
